-
  name: Test Connectivity
  hosts: web_server
  vars:
    ansible_ssh_pass: "{â€Œ{ lookup('csvfile', 'web_server file=credentials.csv delimiter=,') }}"
  tasks:
  - name: Ping target host
    ping:
           data: "Test"
